### ISSUE TITLE
Cannot laod "keras_model.h5"

### ISSUE THREAD

**Issue by oguzhan-bolukbas** [pabangan/IoT_FaceTouchDetection#2]
/Users/XXXXX/opt/anaconda3/envs/TouchFace/bin/python /Users/XXXXX/Desktop/IoT_FaceTouchDetection/app2.py
Traceback (most recent call last):
  File "/Users/XXXXX/Desktop/IoT_FaceTouchDetection/app2.py", line 80, in <module>
    model = tensorflow.keras.models.load_model('keras_model.h5')
  File "/Users/XXXXX/opt/anaconda3/envs/TouchFace/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/Users/XXXXX/opt/anaconda3/envs/TouchFace/lib/python3.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: keras_model.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by oguzhan-bolukbas** [comment]
Caused by tensorflow, not this repo
